### ISSUE TITLE
Linker command failed with exit code 1 

### ISSUE THREAD

**Issue by JJGEight** [imgly/imgly-sdk-ios#11]
Hey,

I have set up my podfile so that it is installing the latest version of imgly on GitHub so that I can compile with 64-bit enabled. However now when I build, I am left with one error: 

clang: error: linker command failed with exit code 1 (use -v to see invocation)

These sort of errors for me usually occur because of failing to include certain Frameworks. However I have checked that the Frameworks I have are the same as the Example App so I should have all of them.

Unfortunately this is all that is thrown up so I haven't got much clue on how I can fix this. Any ideas?

Josh

**Comment by K4stor** [comment]
You fixed it ?
