### ISSUE TITLE
NEGPUImage and simulator issue

### ISSUE THREAD

**Issue by ivishnevsky** [imgly/imgly-sdk-ios#12]
Hi,
I get the latest imgly pod with this line in Podfile:

pod 'imglyKit', :git => 'https://github.com/imgly/imgly-sdk-ios.git'

It runs ok on devices but fails to run on the simulator:

ignoring file /.../Pods/imglyKit/Vendor/NEGPUImage/libNEGPUImage.a, missing required architecture x86_64 in file /.../Pods/imglyKit/Vendor/NEGPUImage/libNEGPUImage.a (2 slices)

I noticed that there's libNEGPUImageSimulator.a file in git, but it's absent in the pod project. When I try to add this file to the imgly pod project manually it doesn't help.

What can I do about this?
Thank you

**Comment by K4stor** [comment]
Hi,

as I pointed out, atm only 32 bit simulators are supported.
As you can see in the example App, I added both, the libNEGPUImage.a and the libNEGPUImageSimulator.a to the final project.
Please do so as well.

![screen shot 2015-01-23 at 11 33 50](https://cloud.githubusercontent.com/assets/1078043/5873145/c8c9100e-a2f3-11e4-94ce-3f823bb45250.png)

The .a files are located in the vendor folder.

In later stages there will be a .framework file, I hope that will remove all the linking trouble.

I hope that helps

**Comment by sascha** [comment]
We've just released version 2 of the SDK, that uses Core Image instead of GPUImage and Swift instead of Objective-C. Please give that version a try - we always appreciate any feedback or pull requests.
