### ISSUE TITLE
BUG - Panoramic photo crop 

### ISSUE THREAD

**Issue by CavalcanteLeo** [imgly/imgly-sdk-ios#136]
There is a bug when you try to crop any panoramic photo. 
The square crop lose in the frame, and can't even crop the image, can't even drag

![2016-03-21 12 21 44](https://cloud.githubusercontent.com/assets/1735944/13923503/aa726d9e-ef5f-11e5-822b-92f3cbe2b261.png)

**Comment by sascha** [comment]
@CavalcanteLeo Thanks for reporting. This is fixed in 3.0, that will be released soon (see #62 for more details).
