### ISSUE TITLE
filterIntensitySlider issue with crop mode

### ISSUE THREAD

**Issue by CavalcanteLeo** [imgly/imgly-sdk-ios#137]
There is a bug on the slider of any filter when the camera is on crop mode.

The slider appears behind the black overlay

![2016-03-28 22 35 09](https://cloud.githubusercontent.com/assets/1735944/14095328/82354ff0-f535-11e5-8350-7ae1c82271e5.png)

**Comment by CavalcanteLeo** [comment]
anyone?

**Comment by K4stor** [comment]
We will release V3 this week.... that bug should be gone then
