### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by ebalassanian** [imgly/imgly-sdk-ios#140]
Hi, is 3.0 available? I'm being asked to upgrade in the console but can't find the branch.

**Comment by sascha** [comment]
Hi, 3.0 is available but not publicly available on GitHub anymore. A closed source version is available for evaluation (either through a dynamic framework or CocoaPods), but if you want to release an app with the SDK you will need to purchase a license (in which case you also receive access to the source code). Please have a look at https://www.photoeditorsdk.com for more details.
