### ISSUE TITLE
Customization of IMGLYEditorMainMenuView

### ISSUE THREAD

**Issue by AndrewSmall** [imgly/imgly-sdk-ios#16]
I have done some work on my fork to allow setting the menu items and some other customization hooks.  I made as few changes to the code as I could think of to accomplish this.  There are perhaps bigger changes that can be made to make the customization a bit easier.  I'd like to know if the current work by others includes enhancing the customizability of the high level classes.  If not I'd like to submit a pull request with my changes.  In either case I'd like to be using imgly/imgly-sdk-ios rather than my own fork.  Please let me know the near-term plans for this level of customization.

**Comment by K4stor** [comment]
Well currently I am working on a complete rewrite of the SDK. If it works out (and it looks good)
In the next version, the views are made mostly with the interface builder. So u can customize them much easier.

What exactly is new on your approach of doing customization ?

**Comment by AndrewSmall** [comment]
I think that your approach using Interface Builder will be a very good improvement.

I have been overriding private methods such as:
### IMGLYEditorViewController
    @interface IMGLYEditorViewController (ProtectedAccess)
    - (void)configureBackButton;
    - (void)configureDoneButton;
    - (void)pushEditorViewController:(IMGLYAbstractEditorBaseViewController *)viewController;
    #pragma mark - sub-editor completion handler
    - (void)completedEditingWithResult:(IMGLYEditorViewControllerResult)result outputImage:(UIImage *)outputImage job:(IMGLYProcessingJob *)job;
    #pragma mark - own completion handler
    - (void)doneButtonTouchedUpInside:(UIButton *)button;
    @end

### IMGLYEditorCropViewController
    @interface IMGLYEditorCropViewController (ProtectedAccess)
    - (void)configureBottomView;
    - (void)setSelectionMode:(IMGLYSelectionMode)selectionMode;
    @end

This was to change the workflow so that after the image was edited, tapping the 'done' button (which was customized to 'next') goes to a customized crop VC that does not have a menu and only supports 16x9.  After tapping done in the crop editor, the edit workflow is complete and the VC dismissed.

I added public property and new init so that I could customize the main menu of the editor by building it with metadata outside and passing the menu into the editor.

### IMGLYEditorViewController
    @property (nonatomic, strong) IMGLYEditorMainMenuView *editorMainMenuView;

### IMGLYEditorMainMenuView
    - (instancetype)initWithFrame:(CGRect)frame imageProvider:(id<IMGLYEditorImageProvider>)imageProvider metaDataArray:(NSArray *)metaDataArray;

**Comment by sascha** [comment]
Version 2, which is a complete rewrite in Swift, is available now. Please give that version a try and let us know if you have any feedback (feel free to create a new issue then). Pull requests are also always much appreciated. Thanks
