### ISSUE TITLE
Update Pod

### ISSUE THREAD

**Issue by aessig** [imgly/imgly-sdk-ios#17]
Hello, 
Would it be possible to update pods to latest version (1.0.8 I think) ? 
Latest one available now is 1.0.4
Regards

**Comment by K4stor** [comment]
sure I'll do it right now

**Comment by K4stor** [comment]
Oh wait, the podspec actually says 1.0.8 already, or did you mean something else ?

**Comment by aessig** [comment]
The podspec inside your repo says 1.0.8, but when I want to use cocoapods, it doesn't work, it only goes up to 1.0.4. https://github.com/CocoaPods/Specs/tree/master/Specs/imglyKit
(Maybe I'm missing something, sorry I'm a newbie).

**Comment by K4stor** [comment]
Yes you are right. I am currently trying to contact the former owner and ask him to add me as owner.

Please be patient

**Comment by aessig** [comment]
Sure, thanks a lot

**Comment by sascha** [comment]
Sorry about the delay. Version 1.0.8 is available through CocoaPods now and is the last version that uses Objective-C and GPUImage. Version 2 is available as well.
