### ISSUE TITLE
Does not support Armv64

### ISSUE THREAD

**Issue by azeemakram-devbatch** [imgly/imgly-sdk-ios#2]
I have noticed that if you are using 64 bit Architecture in you project iOS SDK of img.ly produces 43 linker errors.

To resolve those issues, I just removed the compatibility of 64 bit Architecture as a Valid Architecture in Build Settings.

Regards

**Comment by sascha** [comment]
We've just released version 2 of the SDK, that uses Core Image instead of GPUImage and Swift instead of Objective-C. Please give that version a try - we always appreciate any feedback or pull requests.
