### ISSUE TITLE
how to add exif into image?

### ISSUE THREAD

**Issue by Elankey** [imgly/imgly-sdk-ios#20]
i want add exif data into image file 
how can i do it?

**Comment by sascha** [comment]
The `IMGLYCameraViewController` and the `IMGLYMainEditorViewController` both have an `completionBlock` property that is being passed an `UIImage`. Within that completion block you should be able to write exif data (see http://stackoverflow.com/questions/9006759/how-to-write-exif-metadata-to-an-image-not-the-camera-roll-just-a-uiimage-or-j for some tips).
