### ISSUE TITLE
Segue and using completion block

### ISSUE THREAD

**Issue by chrisr22** [imgly/imgly-sdk-ios#22]
I know you can set the completion block of the editor (to be used without the camera)

	func callEditorViewController() {
	    var editorViewController = IMGLYMainEditorViewController()
	    editorViewController.highResolutionImage = image
	    editorViewController.initialFilterType = .None
	    editorViewController.initialFilterIntensity = 0.5
	    editorViewController.completionBlock = editorCompletionBlock
	}

but is there any way to set the completion block of the editor and still use the camera view controller?

I tried to make a camera completion block to pass the image to the editor view controller: 

	func cameraCompletionBlock(image: UIImage?) {
        let editorViewController = IMGLYMainEditorViewController()
        editorViewController.highResolutionImage = image
        if let cameraController = cameraController {
            editorViewController.initialFilterType = cameraController.effectFilter.filterType
            editorViewController.initialFilterIntensity = cameraController.effectFilter.inputIntensity
        }
        editorViewController.completionBlock = editorCompletionBlock
        
        let navigationController = IMGLYNavigationController(rootViewController: editorViewController)
        navigationController.navigationBar.barStyle = .Black
        navigationController.navigationBar.translucent = false
        navigationController.navigationBar.titleTextAttributes = [ NSForegroundColorAttributeName : UIColor.whiteColor() ]
        
        self.presentViewController(navigationController, animated: true, completion: nil)
    }

but calling the editor completion block, which has a push segue, does not pull up the new view controller which will have the image? I know I did not pass the image yet, but that is because I cannot even get the new view controller to open up (however, NSLogs in the new view controller are working for some reason)

	func editorCompletionBlock(result: IMGLYEditorResult, image: UIImage?) {
        if let image = image where result == .Done {
            NSLog("done")
            self.performSegueWithIdentifier("pushPhoto", sender: self)
        } else {
            NSLog("Cancelled")
            var cameraViewController = IMGLYCameraViewController()
            cameraViewController.completionBlock = cameraCompletionBlock
            
            appDelegate.window?.rootViewController = cameraViewController
        }
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
        if segue.identifier == "pushPhoto" {
            let secondViewController = segue.destinationViewController as! viewPhotoVC
            
           self.presentViewController(secondViewController, animated: true, completion: nil)
        }
    }

Is there an easier way to deal with passing the photo and transitioning from the editor view controller to another view controller?

**Comment by sascha** [comment]
I don't see anything that's wrong with your code. Is the view controller that implements `func editorCompletionBlock(result: IMGLYEditorResult, image: UIImage?)` loaded from a storyboard file (i.e. is `self.storyboard != nil`)?

**Comment by chrisr22** [comment]
yes, it is loaded from a storyboard file. Actually the above code does not even present the editor screen
