### ISSUE TITLE
add 64 bit support in existing code without pulling the latest code

### ISSUE THREAD

**Issue by VishalNarvani** [imgly/imgly-sdk-ios#23]
Hi,

Thanks for this awesome library. :)
I cloned it in mid October, and now issue is i can't upload the app to iTunes as at that time it was missing 64 bit support. So now when i am trying to add arm64 architecture its giving lots of errors. And as i have done so many customisation in original code i cannot pull the latest code. So please anyone can suggest a way how to add 64 bit support in existing code?
Thanks!

**Comment by sascha** [comment]
Hi, 
I'm sorry to say that we do not support version 1.x of the SDK anymore. The complete source code is available in the [legacy-fullSource branch](https://github.com/imgly/imgly-sdk-ios/tree/legacy-fullSource) though and you should be able to add 64 bit support by using that and a newer version of [GPUImage](https://github.com/BradLarson/GPUImage).
