### ISSUE TITLE
Change scale of image taken (both in camera and editor)

### ISSUE THREAD

**Issue by chrisr22** [imgly/imgly-sdk-ios#24]
I am having an issue changing the scale of the image taken, is there a way to easily change the size of the image (so it is 1:1 or something). I have been trying to modify fittedIntoTargetRect() but nothing seems to be working.

Any suggestions?

**Comment by K4stor** [comment]
Hi,
I am not 100% sure I know what u want to do ,
but I  think its the crop function.
In the editor u can choose serveral aspect ratios i.e 4:3 16:9 and 1:1.

If that wont help,pleas consider making a before and after image with photoshop or something alike and upload it here, so we know what it is you want to do.

Regards

**Comment by chrisr22** [comment]
I guess what I'm trying to do is make it so it only takes 1:1 photos. Like Instagram.

**Comment by K4stor** [comment]
Ah ok !

In case u want to use the example as base for your app,
you could set the crop filter right, that will crop the images corretly after they are taken.

In the preview u must add an extra layer that darkens the non-square regions.

Please consider getting a license for deeper support level.
In case u did that already, consider contacting us via email.

**Comment by chrisr22** [comment]
I have tried cropping the original image after the picture but am not having any luck doing so. I have added this to the MainEditorViewcontroller ViewDidLoad method: fixedFilterStack.orientationCropFilter.cropRect = initialCrop and i set the initialCorp to a random Rect

public var initialCrop = CGRectMake(0, 0, 500, 500)

but this does not seem to have any effect

**Comment by K4stor** [comment]
We provided a 'feature/squareMode-laye' branch that will show how to do so.
It will be merged soon
