### ISSUE TITLE
iOS9 Errors

### ISSUE THREAD

**Issue by derekchan2k** [imgly/imgly-sdk-ios#26]
Am getting this 2 errors when using the sdk on iOS9
- CIFilter inputImage has a type that is not supported.
- CIFilter inputIntensity has a type that is not supported.

Will the team look into this? Currently we are doing version checks to prevent iOS9 from using the plug in. Understand that iOS9 is still on beta testing so this may no longer be an issue after the final version of iOS9 is released. 

Thank you for your kind attention

**Comment by derekchan2k** [comment]
oh by the way, the issue occured on iOS9 beta 4 (Build 13A4305g)

**Comment by sascha** [comment]
There is an extra branch with Swift 2 support: https://github.com/imgly/imgly-sdk-ios/tree/feature/swift2
I did not test this with beta 4 and it is a few commits behind master, but I hope it gives you a few hints on how to solve your problems. I'll update the branch when I get a chance to.

**Comment by derekchan2k** [comment]
No worries, thanks sascha!

**Comment by sascha** [comment]
I've updated the branch and it compiles with beta 4 now. Unfortunately running the sample project currently crashes because of a bug in iOS though (http://www.openradar.me/22053289).
