### ISSUE TITLE
Action button missing ! Help!

### ISSUE THREAD

**Issue by HendryZheng** [imgly/imgly-sdk-ios#27]
![screen shot 2015-07-29 at 1 52 44 pm](https://cloud.githubusercontent.com/assets/2715449/8951519/bb50558e-35f8-11e5-9970-bf247934e690.png)
codes :+1: 

func callEditorViewController(image: UIImage) {
        var editorViewController = IMGLYMainEditorViewController()
        editorViewController.highResolutionImage = image
        editorViewController.initialFilterType = .None
        editorViewController.initialFilterIntensity = 0.5
        editorViewController.completionBlock = editorCompletionBlock
        var buttons = editorViewController.actionButtons
        self.presentViewController(editorViewController, animated: true, completion: nil)
    }
    
    func editorCompletionBlock(result: IMGLYEditorResult, image: UIImage?) {
        if(self.pickerChosen == "front"){
            frontPhoto.image = image
        }else if(self.pickerChosen == "back"){
            backPhoto.image = image
        }else if(self.pickerChosen == "side"){
            sidePhoto.image = image
        }else{
            interiorPhoto.image = image
        }

    }

**Comment by sascha** [comment]
Try embedding the `IMGLYMainEditorViewController` inside a `UINavigationController`. This should give you the missing action buttons.

**Comment by HendryZheng** [comment]
Hi Sascha, can give me simple example on embedding inside UINavigationController? My type of view is UIViewcontroller.

**Comment by sascha** [comment]
Try

```swift
let editorViewController = IMGLYMainEditorViewController()
editorViewController.highResolutionImage = image
editorViewController.initialFilterType = .None
editorViewController.initialFilterIntensity = 0.5
editorViewController.completionBlock = editorCompletionBlock

let navigationController = UINavigationController(rootViewController: editorViewController)
navigationController.navigationBar.barStyle = .Black
navigationController.navigationBar.translucent = false
navigationController.navigationBar.titleTextAttributes = [ NSForegroundColorAttributeName : UIColor.whiteColor() ]

self.presentViewController(navigationController, animated: true, completion: nil)
```

**Comment by HendryZheng** [comment]
Thanks a lot Sascha !!! It Works !!!
