### ISSUE TITLE
Ability to start with the front camera

### ISSUE THREAD

**Issue by seviu** [imgly/imgly-sdk-ios#28]
This is more an enhancement for an awesome library. The idea should be adding to IMGLYCameraViewController a boolean property that tells the starts with the front camera. After playing and modifying the code I have seen this is kind of trivial. If you think this makes sense for the imgly sdk I can submit a pull request.

**Comment by K4stor** [comment]
Hi Seviu,

thanks for your effort !
That sounds interesting, may u have the code on Github, so I can review it first ?


With kind regards 
Carsten Przyluczky

On 3 Aug 2015 at 09:36:56, seviu (notifications@github.com) wrote:

This is more an enhancement for an awesome library. The idea should be adding to IMGLYCameraViewController a boolean property that tells the starts with the front camera. After playing and modifying the code I have seen this is kind of trivial. If you think this makes sense for the imgly sdk I can submit a pull request.

**Comment by seviu** [comment]
Ok cool, I will work on the latest version of your library. I did that a few months ago as an experiment but then I threw the code away. I will tell you once I am done.  Thanks a bunch and keep up with this awesome project!
