### ISSUE TITLE
Selected filter in capture mode does not reflect in live capture view when returning from edit mode

### ISSUE THREAD

**Issue by ronnyandre** [imgly/imgly-sdk-ios#3]
How to reproduce:

1. Click the open filters drawer button and select a filter. You can now see that the live camera view is reflecting the selected filter.
2. Take a photo, do whatever you want in edit mode, and return to capture mode.
3. When you now are back in capture mode and open the filters drawer, the active filter is still selected, but the live camera view is not reflecting it.

[See GIF animation here](http://recordit.co/XVURbd8lqA.gif)

**Comment by sascha** [comment]
We've just released version 2 of the SDK, that uses Core Image instead of GPUImage and Swift instead of Objective-C. Please give that version a try - we always appreciate any feedback or pull requests.
