### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by lazyprogram** [imgly/imgly-sdk-ios#37]
I am using objective c. I integrated your project successfully. Could please advice me How to add cancel or close button?

**Comment by lazyprogram** [comment]
Please guide to How to implement completionBlock in objective c

**Comment by sascha** [comment]
@lazyprogram: The cancel button should automatically appear as long as you are embedding the `IMGLYMainEditorViewController` into an `UINavigationController`.

What exactly do you need help with regarding the completionBlock?
