### ISSUE TITLE
Orientation change crashes

### ISSUE THREAD

**Issue by mjlee250** [imgly/imgly-sdk-ios#38]
First, thank you for a great product! I'm getting a crash when running the Example project. The same crash occurs in my app. This is using the latest commit, as of this posting. To reproduce:

Select an existing photo to edit. Tap Orientation. Tap any of the 4 orientation buttons. There is a crash in processWithUIImage: "fatal error: unexpectedly found nil while unwrapping an Optional value"

**Comment by K4stor** [comment]
Hello, 

I am not able to reproduce the crash.
Can you please provide more information ?
What XCode Version are you using ?
What iOS are you targeting ? What device.

Regards

**Comment by vitalrum** [comment]
ios 8.4, iphone 5s
crash "Appname was compiled with optimization - stepping may behave oddly; variables may not be available."
