### ISSUE TITLE
get edited image in objective-C

### ISSUE THREAD

**Issue by y9du** [imgly/imgly-sdk-ios#39]
I incorporated this great sdk into my objective-c project. and this is how I use the cameraViewController

 NSArray * recordingModes = [NSArray arrayWithObjects:[NSNumber numberWithInt:0],[NSNumber numberWithInt:1], nil];
    IMGLYCameraViewController *cameraViewController = [[IMGLYCameraViewController alloc]initWithRecordingModes:recordingModes];
    [self presentViewController:cameraViewController animated:YES completion:nil];

However, I need to access the edited image and pass it to another view controller in objective-C, but the current editorCompletionBlock only saves the edited image to photo library. Is there a way to solve this problem?

**Comment by sascha** [comment]
@y9du: Initialize a `IMGLYMainEditorViewController` inside the `completionBlock` of your `IMGLYCameraViewController` and then present it yourself. That way you can pass a different completion handler to the editor.

**Comment by y9du** [comment]
Can you elaborate more on how to write my own completionBlock for my IMGLYCameraViewController in objective-C? Thanks

**Comment by sascha** [comment]
I hope this helps you:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];

    IMGLYCameraViewController *cameraViewController = [[IMGLYCameraViewController alloc] initWithRecordingModes:@[@(IMGLYRecordingModePhoto), @(IMGLYRecordingModeVideo)]];

    // Needed to avoid retain cycles
    __weak typeof(cameraViewController) weakCameraViewController = cameraViewController;

    cameraViewController.completionBlock = ^(UIImage *image, NSURL *movieURL) {
        __strong typeof(weakCameraViewController) strongCameraViewController = weakCameraViewController;
        
        if (image != nil) {
            IMGLYMainEditorViewController *editorViewController = [[IMGLYMainEditorViewController alloc] init];
            editorViewController.highResolutionImage = image;
            editorViewController.initialFilterType = strongCameraViewController.cameraController.effectFilter.filterType;
            editorViewController.initialFilterIntensity = strongCameraViewController.cameraController.effectFilter.inputIntensity;
            editorViewController.completionBlock = ^(IMGLYEditorResult result, UIImage *editedImage) {
                // You get the edited image here and can do with it whatever you want
            };
            
            IMGLYNavigationController *navigationController = [[IMGLYNavigationController alloc] initWithRootViewController:editorViewController];
            navigationController.navigationBar.barStyle = UIBarStyleBlack;
            navigationController.navigationBar.translucent = NO;
            navigationController.navigationBar.titleTextAttributes = @{ NSForegroundColorAttributeName : [UIColor whiteColor] };
            
            [strongCameraViewController presentViewController:navigationController animated:YES completion:nil];
        }
    };
    
    self.window.rootViewController = cameraViewController;
    [self.window makeKeyAndVisible];
    
    return YES;
}
```

**Comment by JasonGreenAmerica** [comment]
I can't get the completion block to work with swift- can you elaborate on the completionBlock in swift?

-Thanks.

**Comment by K4stor** [comment]
Please be more explicit. What do you mean by not working. 
What is the matter ?

**Comment by JasonGreenAmerica** [comment]
the completion block doesn't fire so i can catch the image from the editorViewController. my above code doesn't work. Do you have a swift snippet that will call the cameraViewController and then get the final image from the editor?

cameraViewController!.completionBlock? = IMGLYCameraCompletionBlock....doesn't work....
