### ISSUE TITLE
Installing through Cocoapods and Swift 2.0

### ISSUE THREAD

**Issue by nyapster** [imgly/imgly-sdk-ios#40]
After installing imgly through CocoaPods in Xcode 7, some of the code has not been updated to be compatible with Swift 2.0. For example, there are ``#``'s in the parameters, or ``@objc`` tags before some class names. 

Going through the source on GitHub, it appears that the code HAS been changed, but the changes are just not reflected on the version installed through CocoaPods (apparently, version 2.3.1).

**Comment by sascha** [comment]
We've just released 2.4.0 which uses Swift 2.
