### ISSUE TITLE
Rotation error.

### ISSUE THREAD

**Issue by legsak1mbo** [imgly/imgly-sdk-ios#41]
Using the library in an Objective-C project. Most things work really well but rotating an image in the editor causes a black screen and the message `<Error>: CGImageCreate: invalid image size: 0 x 0.`

**Comment by K4stor** [comment]
Hi 

We need more info to fix that. 
What exactly are you trying to do ?
How ?

Regards

**Comment by legsak1mbo** [comment]
No problem:-

It looks something like this:-

    IMGLYCameraViewController *cameraViewController = [[IMGLYCameraViewController alloc] init];
    __weak typeof(cameraViewController) weakCameraViewController = cameraViewController;
    
    [cameraViewController setCompletionBlock:^(UIImage *image, NSURL *url) {
        if(image)
        {
            IMGLYNavigationController *navigationController = [[IMGLYNavigationController alloc] init];
            IMGLYMainEditorViewController *editorViewController = [[IMGLYMainEditorViewController alloc] init];
            editorViewController.highResolutionImage = image;
            editorViewController.initialFilterType = nil;
            [editorViewController setCompletionBlock:^(enum IMGLYEditorResult result, UIImage *image) {
                [self dismissViewControllerAnimated:YES completion:nil];
                if(image)
                {
                    //Do something with the image...
                }
            }];
            
            [navigationController setViewControllers:@[editorViewController]];
            [weakCameraViewController presentViewController:navigationController animated:YES completion:nil];
        }
        else
        {
            [self dismissViewControllerAnimated:YES completion:nil];
        }
    }];
    [self presentViewController:cameraViewController animated:YES completion:nil];

Whether I take a photo with the camera or choose an existing one (in the IMGLYCameraViewController) all editing functions then work in the IMGLYMainEditorViewController with the exception of rotation which leads to the aforementioned errors.

**Comment by K4stor** [comment]
Well the code looks ok so far.
What iOS / Device / XCode version, are u building to, and do you have the same issue with the provided example app ?

**Comment by legsak1mbo** [comment]
Xcode 7 for iOS 9. The same issue occurs with the example app as well.

Interestingly, when running in the simulator the error is slightly different:-

    iOS Example[2585] <Error>: CGImageProviderCreate: invalid image provider size: nan x nan.

...which causes the app to crash. Said crash occurs on line 116 of IMGLYPhotoProcessor.swift:-

    let filteredCGImage = CIContext(options: nil).createCGImage(filteredCIImage!, fromRect: filteredCIImage!.extent)
