### ISSUE TITLE
Building in XCode 7

### ISSUE THREAD

**Issue by tygerbw** [imgly/imgly-sdk-ios#42]
I cannot build in XCode 7 as IMGLY was build using Swift 1.2.  The automatic conversion to 2.0 does not seem to resolve the issue, leaving many errors.  I would solve them myself as they seem like syntax errors but I do not know Swift yet.

**Comment by K4stor** [comment]
We are working on a SWIFT 2.0 Version, should be available soon

**Comment by tygerbw** [comment]
awesome!

**Comment by sascha** [comment]
We just released 2.4.0 with Swift 2 support earlier today actually.

**Comment by tygerbw** [comment]
whaaaa!?  You guys rock!  Will try it out now :)
