### ISSUE TITLE
Step by Step Documentation

### ISSUE THREAD

**Issue by emreavsar** [imgly/imgly-sdk-ios#43]
Hey there,

I really like this SDK, but somehow I don't understand your (small) documentation. Can you maybe please provide a step by step integration guide?

I also tried the examples, but i cannot find a project where I see the controllers so that I can adapt to my project.

If there is a bigger documentation, please make it more present in the readme.md file.

thx
emre

**Comment by emreavsar** [comment]
btw I'm not meaning the pod install stuff, this is already done. I mean how to use it. :)

**Comment by K4stor** [comment]
HI

Well the example app is a documentation itself, showing all the steps and settings needed to get going.

**Comment by emreavsar** [comment]
Ok maybe I'm just not seeing it. I did this to check it out:
1) download zip of master
2) open Examples -> iOS Example.xcodeproj
3) Where do I now see the storyboard, or something like this? 
3.1) I only see the AppDelegate.swift and the LaunchScreen
3.2) Or is it inside imglyKit.xcodeproj? (i thought this is only the lib itself)

thx for the very fast answer btw.

**Comment by K4stor** [comment]
We chose to create the views via code. In our experience thats the most robust way.
So the lib contains the views also. The sample shows how to use the CameraViewController, that will
display the photo-take dialog. And then its hand over to the Editor also, provided by the SDK.

**Comment by emreavsar** [comment]
OK great, so I'm not that wrong with asking for more doc, am I? :)

Maybe it's easier when I ask this way: How can I achieve in an own ViewController these things:
1) Open imgly image capture
2) Capture image and apply filter
3) Get the result image back to my ViewController

Or is this not possible anyway?

**Comment by K4stor** [comment]
We will add a better docu soon. 
Atm we are working on new features requested by customers.

For you:
you init the ```IMGLYCameraViewController``` and set a completion-block.
That should have the type ```IMGLYCameraCompletionBlock```. 
You will get the Image taken then you can initiate a ```IMGLYMainEditorViewController``` and you can edit.

If you need more information please read the code, it holds all the answers :-)

**Comment by emreavsar** [comment]
ok, fair enough. I'll try it. thx
