### ISSUE TITLE
I got 166 error while opening your project in XCode 6.3

### ISSUE THREAD

**Issue by niravspaceo** [imgly/imgly-sdk-ios#44]
Hello,

I am trying to run your project in Xcode 6.3 but It is giving me lots of errors. I checked the Issue Navigator and I saw that all errors are because of Swift Compiler Error. So how to solve this ?

Thanks.

**Comment by K4stor** [comment]
Hello, 

please update to XCode 7.0. We use SWIFT 2.0 now so the 6.3 compiler won't be able to build the project.
