### ISSUE TITLE
Feature Request: Cancel button on CameraViewController

### ISSUE THREAD

**Issue by chenzeyu** [imgly/imgly-sdk-ios#45]
Thanks for the awesome library.

Currently there are photo library button and filter button on bottom, where user cannot cancel to dismiss the current CameraViewController.

 I hope there can be an option to choose from using filter button or cancel button on right bottom corner.

**Comment by Spacelapp** [comment]
+1 :)

**Comment by tobiasfeistmantl** [comment]
+1

**Comment by pasevin** [comment]
+1 :]

**Comment by K4stor** [comment]
Good point, I add this to the ToDo !
