### ISSUE TITLE
How to perform segue to pass edited image

### ISSUE THREAD

**Issue by y9du** [imgly/imgly-sdk-ios#48]
Hi,

I have posted an issue before and hank you for showing me how to get the edited image by modifying the completion block. I am now able to pass the edited image to the viewcontroller where the IMGLYCameraViewController is initiated; however I am stuck when I am trying to pass the edited image to a new viewcontroller using segue. I was wondering where I did wrong. Below is the code:

- (IBAction)imgProcessing:(id)sender {
    
    IMGLYCameraViewController *cameraViewController = [[IMGLYCameraViewController alloc] initWithRecordingModes:@[@(IMGLYRecordingModePhoto), @(IMGLYRecordingModeVideo)]];
    
    // Needed to avoid retain cycles
    __weak typeof(cameraViewController) weakCameraViewController = cameraViewController;
    
    cameraViewController.completionBlock = ^(UIImage *image, NSURL *movieURL) {
        __strong typeof(weakCameraViewController) strongCameraViewController = weakCameraViewController;
        
        if (image != nil) {
            IMGLYMainEditorViewController *editorViewController = [[IMGLYMainEditorViewController alloc] init];
            editorViewController.highResolutionImage = image;
            editorViewController.initialFilterType = strongCameraViewController.cameraController.effectFilter.filterType;
            editorViewController.initialFilterIntensity = strongCameraViewController.cameraController.effectFilter.inputIntensity;
            editorViewController.completionBlock = ^(IMGLYEditorResult result, UIImage *editedImage) {
                // You get the edited image here and can do with it whatever you want
                if (result == IMGLYEditorResultDone) {
                
                    [_editedImage setImage:editedImage];

                    [self performSegueWithIdentifier:@"pushImage" sender:self];
                                 
                }
                else{
                   [self dismissViewControllerAnimated:YES completion:NULL];
                }
                
                            };
            
            IMGLYNavigationController *navigationController = [[IMGLYNavigationController alloc] initWithRootViewController:editorViewController];
            navigationController.navigationBar.barStyle = UIBarStyleBlack;
            navigationController.navigationBar.translucent = NO;
            navigationController.navigationBar.titleTextAttributes = @{ NSForegroundColorAttributeName : [UIColor whiteColor] };
            
            [strongCameraViewController presentViewController:navigationController animated:YES completion:nil];
        }
    };
    
        [self presentViewController:cameraViewController animated:YES completion:nil];
    
    
    }

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
  {
    if ([segue.identifier  isEqual: @"pushImage"]){
         PostViewController *Post= [segue destinationViewController];
        Post.image = _editedImage.image;
        [self presentViewController:Post animated:YES completion:nil];
    }
}

**Comment by JasonGreenAmerica** [comment]
+1 
for swift

**Comment by K4stor** [comment]
What is the matter ? Where are you stuck ? What should happen, but doesn't :D

**Comment by JasonGreenAmerica** [comment]
Hi K4stor,  I need to handle image after the user selects done in the image editor. Looking at the sample above.. I attempted to code in swift this, but the completionBlock doesn't fire. 

@IBAction func cameraTouchUpInside(sender: UIBarButtonItem) {
        cameraViewController = IMGLYCameraViewController(recordingModes: [.Photo, .Video])
        //cameraViewController!.completionBlock? = (image: UIImage?, url: NSURL?) -> () {
            
        //}
        cameraViewController!.completionBlock? = IMGLYCameraCompletionBlock
        cameraViewController!.maximumVideoLength = 15
        navigationController?.pushViewController(cameraViewController!,animated: true)
    }
    
    func IMGLYCameraCompletionBlock(image: UIImage?, url: NSURL?) {
        if(image != nil)
        {
            var editorViewController = IMGLYMainEditorViewController();
            editorViewController.highResolutionImage = image;
            editorViewController.initialFilterType = cameraViewController.cameraController!.effectFilter.filterType;
            editorViewController.initialFilterIntensity = cameraViewController.cameraController!.effectFilter.inputIntensity;
            editorViewController.completionBlock = IMGLYEditorCompletionBlock
            cameraViewController.presentViewController(editorViewController, animated: true, completion: nil)
        }
    }
    func IMGLYEditorCompletionBlock(result: IMGLYEditorResult?, editedImage: UIImage?){
        var postView = PostViewController();
        postView.postImageView.image = editedImage;
        navigationController?.pushViewController(postView,animated: true)

        }

**Comment by sascha** [comment]
@JasonGreenAmerica: Could you send me a link to some sample code please?

**Comment by wizardkhalifard** [comment]
@sascha Im also having problems the same problem can you please help me? Im stuck on passing the edited image to my new view controller so I can save it and send it as a message.

**Comment by sascha** [comment]
@wizardkhalifard: Do you have any code that you can show me?

**Comment by K4stor** [comment]
It would be great if one of you guys could upload his project somewhere
so we could compile and test it our selfs...

**Comment by wizardkhalifard** [comment]
@sascha I can share my project on google drive, can i have your email? If you're willing to help @K4stor

**Comment by wizardkhalifard** [comment]
However this is what I have in my New view controller so far
func showCamera(){
        let imagePicker = IMGLYCameraViewController(recordingModes: [.Photo, .Video])
        imagePicker.maximumVideoLength = 10
        imagePicker.squareMode = false

        imagePicker.completionBlock? = IMGLYCameraCompletionBlock
        navigationController?.pushViewController(imagePicker,animated: true)
        self.tabBarController?.tabBar.hidden = true
        
        //presentViewController(imagePicker, animated: true, completion: nil)
    }
    
    func IMGLYCameraCompletionBlock(image: UIImage?, url: NSURL?) {
        if(image != nil)
        {
            let editorViewController = IMGLYMainEditorViewController();
            editorViewController.highResolutionImage = image;
            editorViewController.initialFilterType = imagePicker.cameraController!.effectFilter.filterType;
            editorViewController.initialFilterIntensity = imagePicker.cameraController!.effectFilter.inputIntensity;
            editorViewController.completionBlock = IMGLYEditorCompletionBlock
            imagePicker.presentViewController(editorViewController, animated: true, completion: nil)
        }
    }
    func IMGLYEditorCompletionBlock(result: IMGLYEditorResult?, editedImage: UIImage?){
       
    }

**Comment by K4stor** [comment]
Sure, send it to kastor@9elements.com

**Comment by wizardkhalifard** [comment]
sent it! Should communicate via email

**Comment by sascha** [comment]
@JasonGreenAmerica @wizardkhalifard: The problem with your code is that you are only setting the completion block of the `IMGLYCameraViewController` if it is not `nil`, which it is.

You should write `cameraViewController.completionBlock = IMGLYCameraCompletionBlock` instead of `cameraViewController.completionBlock? = IMGLYCameraCompletionBlock`

**Comment by wizardkhalifard** [comment]
Im able to pass images now, how do i retrieve and even edit videos?

**Comment by TrabelsiAchraf** [comment]
I use the last version 3.0 how can I get the edited image ?

**Comment by sascha** [comment]
@TrabelsiAchraf Please refer to our documentation at https://www.photoeditorsdk.com/documentation/ios/usage#add-a-photoeditviewcontroller

**Comment by TrabelsiAchraf** [comment]
this is my code :

private func customizeCameraController() {
let configuration = Configuration() { builder in
builder.configureCameraViewController{ options in
options.recordingModeButtonConfigurationClosure = { button, _ in
button.setTitleColor(UIColor.grayColor(), forState: .Normal)
button.setTitleColor(UIColor.redColor(), forState: .Selected)
}
}

builder.configurePhotoEditorViewController { options in

}
}

let cameraViewController = CameraViewController(configuration:
configuration)
cameraViewController.completionBlock = {image, url in

let photoEditViewController = PhotoEditViewController(photo: image!)
let toolStackController = ToolStackController(photoEditViewController:
photoEditViewController)
toolStackController.delegate = cameraViewController


toolStackController.navigationItem.title = "Editor"
toolStackController.navigationItem.leftBarButtonItem =
UIBarButtonItem(barButtonSystemItem: .Cancel, target:
photoEditViewController, action: ‪#‎selector‬
<https://www.facebook.com/hashtag/selector?source=feed_text&story_id=10206420457167071>
(PhotoEditViewController.cancel(_:)))
toolStackController.navigationItem.rightBarButtonItem =
UIBarButtonItem(barButtonSystemItem: .Save, target:
photoEditViewController, action:
#selector(PhotoEditViewController.save(_:)))

let navigationController = UINavigationController(rootViewController:
toolStackController)
navigationController.navigationBar.translucent = false
navigationController.navigationBar.barStyle = .Black


cameraViewController.presentViewController(navigationController, animated:
true, completion: nil)

//cameraViewController.presentViewController(toolStackController, animated:
true, completion: nil)
}


if let window = UIApplication.sharedApplication().delegate?.window! {
window.tintColor = UIColor.whiteColor()
window.rootViewController = self
window.makeKeyAndVisible()
}

self.presentViewController(cameraViewController, animated: true,
completion: nil)
}


+++++

But the problem after reading the documentation i DON'T know how can I get
the edited image result.

2016-04-12 10:24 GMT+01:00 Sascha Schwabbauer <notifications@github.com>:

> @TrabelsiAchraf <https://github.com/TrabelsiAchraf> Please refer to our
> documentation at
> https://www.photoeditorsdk.com/documentation/ios/usage#add-a-photoeditviewcontroller
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/imgly/imgly-sdk-ios/issues/48#issuecomment-208813249>
>



-- 
----------------------------
*Trabelsi Achraf*
Élève Ingénieur à *ESPRIT *: Ecole Supérieur Privée d'Ingénierie et de
Technologies
Tél : +216 22 925 451
Portfolio : http://trabelsi-achraf.tk/
