### ISSUE TITLE
imgly-sdk-ios Custom stickers!

### ISSUE THREAD

**Issue by joelbanzatto** [imgly/imgly-sdk-ios#50]
Hello,

How can I use my own stickers in imgly-sdk for iOS?
Is there a protocol or a block or an attribute?

Thanks.

**Comment by krloxzs** [comment]
hi, you can use new stickers if you...
1) edit the xcasses in the frontend folder
2) adding a new xcasses and editing the IMGLYStickersDataSource.swift to read your stickers

if you need help using this sdk sendme a mail ...am using this in a proyect :D
