### ISSUE TITLE
NSURLSession-error

### ISSUE THREAD

**Issue by Bragegs** [imgly/imgly-sdk-ios#54]
Hello!
I get this error when presenting the cameraviewController:

NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

Something I can type into info.plist (except from NSAllowsArbitraryLoads-temporaryfix) to remove it?

**Comment by sascha** [comment]
@Bragegs: Thank you for reporting this. We will fix our certificate, so you shouldn't have to add anything to your Info.plist. In the meantime you can safely ignore the error as we are only trying to connect to our servers to check if you are running the latest version of the SDK and give you a warning if you are not.
