### ISSUE TITLE
Why when IMGLYRecordingModePhoto mode used the permission for microphone access displayed?

### ISSUE THREAD

**Issue by YaroslavBabenko** [imgly/imgly-sdk-ios#57]
Why when IMGLYRecordingModePhoto mode used the permission for microphone access displayed? When I want use sdk only for photo I don't need microphone.

**Comment by sascha** [comment]
@YaroslavBabenko: Thanks for reporting. This is a known problem and we are working on it.

**Comment by sascha** [comment]
This has been fixed in PR #71.
