### ISSUE TITLE
issue cropping images that are not native "photo" resolution 

### ISSUE THREAD

**Issue by ebalassanian** [imgly/imgly-sdk-ios#62]
![img_1888](https://cloud.githubusercontent.com/assets/251664/12247758/53b4aeb2-b86a-11e5-990f-7d2b8668d010.PNG)
The crop rectangle is mispositioned when selecting images from the camera roll that have lower resolution than images taken in img.ly.

**Comment by sascha** [comment]
Fixed in a5103655caeac608c09e064621de187bb56d7196. Thanks
