### ISSUE TITLE
missing required architecture x86_64

### ISSUE THREAD

**Issue by allabttony** [imgly/imgly-sdk-ios#7]
```
ld: warning: ignoring file /Users/tony/Dev/xxx/Pods/imglyKit/Vendor/NEGPUImage/libNEGPUImage.a, missing required architecture x86_64 in file /Users/tony/Dev/xxx/Pods/imglyKit/Vendor/NEGPUImage/libNEGPUImage.a (3 slices)
Undefined symbols for architecture x86_64:
```
how can i fix this problem?

**Comment by sascha** [comment]
We've just released version 2 of the SDK, that uses Core Image instead of GPUImage and Swift instead of Objective-C. Please give that version a try - we always appreciate any feedback or pull requests.
