### ISSUE TITLE
GPUImage

### ISSUE THREAD

**Issue by onmyway133** [imgly/imgly-sdk-ios#9]
Can we change the podspec to include GPUImage as a Pod dependency? Why should we use NEGPUImage?

**Comment by VishalNarvani** [comment]
@hexrain , Hey thanks for this awesome kit :) 
Exactly when are you planning to provide support for iPhone 6 and iPhone 6 plus?

**Comment by K4stor** [comment]
Workin on it in this very moment :smile: 

In the next days

**Comment by Rainburst** [comment]
@VishalNarvani, I'm not sure if you were asking me, but my fork supports new iPhones as far as I know. But I'm suggesting to wait for @k4stor release, there should be more filters and optimizations.

**Comment by AndrewSmall** [comment]
@K4stor I am getting crashes on iPhone 6 and 6+ and even on a iPhone 5S.  These are when using the IMGLYCameraViewController.  My boss is anxious for me to fix this.  I haven't been seeing crashes with MHIMGLYEditorViewController.  Is this something you are working on fixing?  If so when can you release?  I may have to use UIImagePickerController for the camera for now.

**Comment by K4stor** [comment]
Sorry to hear that Andrew!
Can u describe exactly how the crashes happen? Like what you are doing and so on ?
Yes I am working on a complete rewrite without GPUImage just CoreImage.
It will take about 2 weeks for me to put out a beta.
You could also use the build in Camera Controller of iOS to take Photos for now and then hand em over to the IMGLYEditorViewController

**Comment by K4stor** [comment]
Also I will release the full source as new branch in the next hour

**Comment by AndrewSmall** [comment]
On my iPhone 6+ iOS 8.1 I can take 1 or 2 photos but then the next photo crashes right after the shutter effect and the still image shows for a split second.  Xcode 6 always shows "Lost connection to "iPhone name".  The debugger is not functional at this point.  I Googled this condition and SO says this is a memory error.  The Leaks Instrument shows memory warnings (LLDB does not) but at the time of the crash I don't see memory growth.

**Comment by K4stor** [comment]
PLease try the full source version as should be able to get better info

**Comment by sascha** [comment]
We've just released version 2 of the SDK, that uses Core Image instead of GPUImage and Swift instead of Objective-C. Please give that version a try - we always appreciate any feedback or pull requests.
